# 配布アプリの一覧。アプリを追加する場合は以下のリストにエントリを足し、
# templates/apps/<slug>.html を用意し、filenameがあればstatic/downloads/に配布ファイルを置く。
# filenameがNoneのアプリは「準備中」扱いになり、ダウンロードボタンは表示されない。
# github_urlがあれば「準備中」バッジの代わりにソース公開中のバッジとリンクを表示する。
# 最終更新日は配布ファイルのmtimeから自動算出するため、ここには書かない。
# changelogは手書きの更新履歴（新しい順）。無くても動くので、更新時に書ければ追記する。
# versionは手書きのバージョン番号（例: "0.2.1"）。無くても動くので、正式なバージョン
# 番号を持たないアプリ（aquafox-jaなど）は省略してよい。最終更新日の隣に表示される。
APPS = [
    {
        "slug": "aquafox-ja",
        "name": "Aquafox 日本語化パック",
        "name_en": "Aquafox Japanese Localization Pack",
        "tagline": "PowerPC Mac 向けブラウザ「Aquafox」を日本語表示にする言語パック",
        "tagline_en": "A language pack for Aquafox that adds Japanese UI support to the PowerPC Mac browser.",
        "platform": "PowerPC Mac (Tiger) 向け",
        "filename": "aquafox-ja.xpi",
        "category": "app",
        "comment": "みなさん英語わかります？読めたとしても直感的に理解できます？私は無理です。一応受験も経験しましたし単語も覚えました。でも単語が繋がった瞬間に暗号に変わりませんか？ そんな私のために作りました。",
        "comment_en": "Can everyone actually read English? Even if you can, does it click intuitively? I can't. I studied for entrance exams, memorized the words — but the moment they string together into a sentence, it might as well be a cipher. Made this for people like me.",
    },
    {
        "slug": "aquafinder",
        "name": "AquaFinder",
        "name_en": "AquaFinder",
        "tagline": "Mac OS X Tiger〜Snow Leopard時代のFinderを現行Macで再現したファイラー",
        "tagline_en": "A classic Finder-style file manager that recreates the Tiger-to-Snow Leopard experience on modern Macs.",
        "platform": "現行macOS (Catalina以降 / Intel・Apple Silicon) 向け",
        "filename": "AquaFinder.dmg",
        "version": "0.2.6",
        "github_url": "https://github.com/watermark-hd/AquaFinder",
        "category": "app",
        "comment": "現場を退いたおじさんが今のM2 Macを使って物足りなさの原因を探ってたどり着いた成果物。",
        "comment_en": "What an old-timer who left the field for good ended up building, after digging into why a brand-new M2 Mac still felt like something was missing.",
        "changelog": [
            {
                "date": "2026-09-13",
                "note": "「ファイル」メニューに「上の階層に移動」(⌘U)を追加。選択中のファイル・フォルダを、今いる場所の親フォルダへ直接移動できます（カラム表示で数階層深いところを選んでいても正しくその親へ）。今までは移動先のフォルダまで自分で辿ってウィンドウを2枚並べてドラッグするしかありませんでした。取り消し(⌘Z)にも対応",
                "note_en": "Added File > Move to Enclosing Folder (⌘U). Moves the selected file or folder directly into the parent of wherever it currently sits — even several levels deep in Column View — without navigating there yourself and dragging between two windows. Undo (⌘Z) works with it too",
            },
            {
                "date": "2026-09-13",
                "note": "アイコン表示で横長・縦長の画像が正方形に押し潰されて表示される不具合を修正。クイックルック中に上下キーで移動すると表示中の並び順と無関係なファイルに飛ぶ不具合を修正。カラム表示で文字サイズ設定を大きくしても文字・アイコンが小さいままだった不具合を修正",
                "note_en": "Fixed landscape/portrait images being squashed into squares in Icon View thumbnails. Fixed Quick Look's up/down navigation jumping to unrelated files instead of following the folder's actual on-screen order. Fixed Column View's text and icons staying small even after raising the text-size setting",
            },
            {
                "date": "2026-09-09",
                "note": "サイドバーの「共有」項目に接続先ホスト名を表示（例：「書類 (192.168.11.12)」）。Apple IDのファイル共有で他のMacの「書類」「ダウンロード」をSMBマウントすると、ローカルの同名フォルダと見分けがつかなかったため。「場所」「デバイス」の項目は変更なし",
                "note_en": "SHARED sidebar items now show their source host — e.g. \"Documents (192.168.11.12)\". When you SMB-mount another Mac's own Documents/Downloads via Apple ID file sharing, they came out with the exact same name as your local folders under PLACES; the host suffix tells them apart. PLACES and DEVICES items are unchanged",
            },
            {
                "date": "2026-08-29",
                "note": "Dropbox等の同期ツールや低速なネットワーク共有で、短時間に大量のファイル変更イベントが発生すると、リスト表示の行が一時的に重複・消失して見える不具合を修正。変更イベントが300ms静かになるまでまとめてから再読み込みするように変更",
                "note_en": "Fixed rows briefly duplicating or disappearing in List view when a sync tool (Dropbox, etc.) or a slow network share fired a burst of file-change events in quick succession. Now waits for a 300ms quiet period before reloading, instead of reloading on every single event",
            },
        ],
    },
    {
        "slug": "aqualink",
        "name": "AquaLink",
        "name_en": "AquaLink",
        "tagline": "PowerPC Mac G4をNAS化する、SMB3対応ファイルブラウザ",
        "tagline_en": "A file browser for turning a PowerPC Mac G4 into an SMB3-ready NAS-like file server.",
        "platform": "PowerPC Mac (Tiger) 向け",
        "filename": "AquaLink.zip",
        "version": "0.5.17",
        "github_url": "https://github.com/watermark-hd/ppc-mac-modernization/tree/main/smb3/AquaLink",
        "category": "app",
        "comment": "PowerMac G4、iBook G4、iMac G5（未検証） そんなマシンたちにまだ活躍してもらうために作りました。昔のデータが入りっぱなし、元データを作った時の環境が知りたい。そんな事情で作りました。",
        "comment_en": "Made so PowerMac G4s, iBook G4s, and (untested) iMac G5s can keep earning their keep. Old data still sitting on them, and I wanted to see it in the environment it was actually made in — that's the real reason.",
        "changelog": [
            {
                "date": "2026-09-12",
                "note": "PowerMac G4実機で見つかった、ファイル一覧で行をクリック後にスクロールすると落ちることがある不具合を修正。ファイル名のアイコン表示に使っていた仕組みを、AppleのNSCellが標準で保証する方式に作り直し、機種によって起きる可能性のあるクラッシュの原因を根本から断った",
                "note_en": "Fixed a crash in the file list found on a real PowerMac G4, most reliably triggered by clicking a row and then scrolling. The icon-display mechanism for filenames was rebuilt on Apple's own standard NSCell facility, removing the underlying cause of a hardware-dependent crash.",
            },
            {
                "date": "2026-09-11",
                "note": "アドレス欄のプルダウンで、発見したサーバーの表示を「名前 — IPアドレス」から名前だけに短縮(選ぶと今まで通りIPが自動で入る)。また、接続に成功したらウィンドウのタイトルバーに接続先(アドレス/共有名)を表示するように(小さなラベルだけでは見落とされていたため)",
                "note_en": "The discovered-server dropdown now shows just the name instead of \"name — IP address\" (too long to read in the popup); picking one still fills in the IP automatically. Also, a successful connection now shows the target (address/share) in the window's title bar, since the small path label alone was easy to miss.",
            },
            {
                "date": "2026-09-11",
                "note": "一部の環境で「取り外す」が、管理者パスワードを入力しても「Operation not permitted」で失敗し続ける不具合を修正。mount_webdav自身と同じ方式(setuid rootの専用の小さなプログラムをアプリに同梱)で取り外すようにし、パスワードダイアログもターミナルも使わずに確実に外せるように(初回だけ準備のためのパスワード入力が必要)。あわせて、「取り外す」ボタンの表示がFinderから直接取り出した後などに古いまま残る不具合と、取り外し後にデスクトップのアイコンが残ってしまうことがある不具合も修正",
                "note_en": "Fixed \"Unmount\" repeatedly failing with \"Operation not permitted\" on some setups, even after entering an admin password. It now unmounts the same way /sbin/mount_webdav itself does — a small setuid-root helper bundled with the app — so it works reliably without a password dialog or Terminal (a one-time admin password is still needed to set the helper up). Also fixed the \"Unmount\" button sometimes getting stuck after the volume was ejected directly from Finder, and a leftover desktop icon that could linger after unmounting.",
            },
            {
                "date": "2026-09-10",
                "note": "メニューバーに「編集」メニュー(コピー/ペースト/全選択など)を追加。これまで手組みメニューだったため ⌘C / ⌘V がどのテキスト欄でも効かなかったのを解消。また「Finderに接続」でマウントに成功したら、そのフォルダをFinderで自動的に開くように(何がどこにマウントされたか分かりにくかったため。マウント先はAquaLinkを動かしているマシン側です)",
                "note_en": "Added a standard Edit menu (Copy/Paste/Select All, etc.) to the menu bar \u2014 the hand-built menu had none, so \u2318C / \u2318V did nothing in any text field. Also, a successful \"Connect in Finder\" mount now opens that folder in Finder, since it wasn't obvious what got mounted where (it mounts on the machine running AquaLink).",
            },
            {
                "date": "2026-09-10",
                "note": "「Finderに接続」(WebDAVマウント)の失敗が、ウィンドウ下部に小さく出るだけで気づきにくかったのをダイアログでも表示するように。また、mount_webdav コマンドの管理者権限(setuid)がOSアップデート等で外れているとマウントが必ず失敗するため、事前に検知して復旧コマンドを案内するように",
                "note_en": "\"Connect in Finder\" (WebDAV mount) failures were only shown as a small line at the bottom of the window; they now also raise a dialog. AquaLink also checks whether mount_webdav still has its setuid (admin) bit \u2014 OS updates can strip it, which makes every mount fail \u2014 and points you at the one-line fix if it's gone.",
            },
            {
                "date": "2026-09-10",
                "note": "アドレス欄のプルダウンに、LAN上のSMBサーバー(NASや共有中のMac)をBonjourで自動発見して表示するように。IPアドレスを知らなくても、一覧から選ぶだけで繋げます(選ぶとIPアドレスが自動で入ります)。共有名・パスワードは従来通り入力してください",
                "note_en": "The address drop-down now discovers SMB servers on your LAN (NAS boxes, Macs with sharing on) via Bonjour, so you can connect without knowing the IP — just pick it from the list and the IP is filled in. Enter the share name and password as before.",
            },
            {
                "date": "2026-09-06",
                "note": "ファイルブラウザの列ヘッダ(名前・サイズ・更新日時)をクリックしてソートできるように。再クリックで昇順/降順を反転、▲▼で現在の並び順を表示。フォルダは常に先頭",
                "note_en": "The file browser's column headers (Name, Size, Modified) are now clickable to sort. Click again to flip ascending/descending, with a ▲▼ indicator for the current order. Folders always stay on top.",
            },
            {
                "date": "2026-09-06",
                "note": "ファイルブラウザの一覧を Transmit / Cyberduck 風に刷新（見た目中心）。名前列の行頭にフォルダ/ファイルのアイコンを表示し、代わりに「種類」列を廃止。「更新日時」列を追加（ファイル本来の更新日時を「2026-09-06 | 14:32」形式で表示）。サイズ・更新日時は右寄せ＆固定幅で、ウィンドウを広げると名前列だけが伸びる。全列を標準システムフォントに統一",
                "note_en": "Reworked the file list toward a Transmit/Cyberduck style (mostly cosmetic). The Name column now leads with a folder/file icon, so the text \"Kind\" column is gone. Added a \"Modified\" column showing each file's own timestamp as \"2026-09-06 | 14:32\". Size and Modified are right-aligned and fixed width; only the Name column grows when the window widens. All columns use the standard system font.",
            },
            {
                "date": "2026-09-06",
                "note": "ファイルブラウザ画面のUIをまとめて調整（見た目中心）。「上へ」ボタンを「▲ 上へ」表記に変更し(ブラウザの戻る/進むと紛らわしかったため)、Finderと同じ ⌘↑ ショートカットを追加。角丸ボタンの上辺が描画で欠けていた不具合を修正。一覧に .DS_Store 以外の隠しファイル(.lesshst 等)が出ていたのを、ドットファイル全般を非表示にして解消（表示上のフィルタのみ。ファイルは削除しません）",
                "note_en": "A batch of file-browser UI tweaks (mostly cosmetic). The \"Up\" button now reads \"▲ Up\" (it was easily mistaken for browser back/forward) and takes Finder's ⌘↑ shortcut. Fixed the top edge of the rounded buttons being clipped. Dotfiles other than .DS_Store (.lesshst and the like) were showing in the list; now all dotfiles are hidden — a display filter only, nothing is deleted.",
            },
            {
                "date": "2026-09-01",
                "note": "接続失敗時のエラーメッセージが2行目(詳細情報)を表示できていなかった不具合を修正（ステータス表示欄が1行専用だったため。ダイアログでも表示するよう変更）",
                "note_en": "Fixed connection error messages not showing their second (detail) line — the status field was single-line only. Now also shown in a dialog.",
            },
            {
                "date": "2026-08-31",
                "note": "PPCPortsなどタグ付きリリースのlibsmb2でSMB2_SEC_NTLMSSPが未定義でビルドが失敗する不具合を修正（libsmb2本体側で公開ヘッダへの反映がまだのため、互換定義を追加）",
                "note_en": "Fixed a build failure (SMB2_SEC_NTLMSSP undeclared) against tagged libsmb2 releases such as PPCPorts' — added a compat definition since upstream hasn't moved it to a public header in any release yet.",
            },
            {
                "date": "2026-08-29",
                "note": "直前の修正でMakefileに加えた変更が、Leopard/Snow Leopardでのビルドを壊していたのを修正（システム側のヘッダーが実際に無い場合のみSDKにフォールバックするよう変更）",
                "note_en": "Fixed a regression from the previous fix: a Makefile change was breaking builds on Leopard/Snow Leopard. Now only falls back to the SDK when the system's own headers are actually missing.",
            },
            {
                "date": "2026-08-29",
                "note": "PPCPorts経由(Kerberos対応込み)でビルドしたlibsmb2で、認証がKerberos経由を試みて失敗し接続できない不具合を修正（NTLM認証を明示するよう変更）",
                "note_en": "Fixed a connection failure on libsmb2 built via PPCPorts (with Kerberos support): authentication was attempting Kerberos first and failing, so NTLM is now explicitly requested instead.",
            },
            {
                "date": "2026-08-28",
                "note": "SMB3暗号化を必須にするオプションを追加。実装過程で、libsmb2本体のビッグエンディアン環境向けバグ（暗号化ヘッダーのSessionIdがエンディアン変換されていなかった）を発見・修正し、上流に報告した",
                "note_en": "Added an option to require SMB3 encryption. While implementing it, found and fixed a big-endian bug in libsmb2 itself (the encrypted header's SessionId wasn't byte-swapped for the wire) and reported it upstream.",
            },
            {
                "date": "2026-08-23",
                "note": "管理者権限での実行時にumountコマンドが見つからず失敗する不具合を修正（/sbin/umountをフルパスで指定するように変更）",
                "note_en": "Fixed umount failing under administrator privileges by calling it via its full path (/sbin/umount)",
            },
            {
                "date": "2026-08-20",
                "note": "UIを英語対応(日本語/英語切り替え)",
                "note_en": "Added English UI support (switchable between Japanese and English)",
            },
            {
                "date": "2026-08-20",
                "note": "メニューバーが開かなくなる不具合を修正",
                "note_en": "Fixed an issue where the menu bar would fail to open",
            },
        ],
    },
    {
        "slug": "ppc-claude-agent",
        "name": "PPC Claude Agent",
        "name_en": "PPC Claude Agent",
        "tagline": "PowerPC Mac (Tiger)のターミナルからAIと会話できる、Perl製の自己完結型エージェント（Claude / Gemini / ローカルLLM対応）",
        "tagline_en": "A self-contained Perl agent that lets you talk to an AI from the Terminal on a PowerPC Mac (Tiger) — supports Claude, Gemini, and local LLMs.",
        "platform": "PowerPC Mac (Tiger) 向け",
        "filename": "ppc-claude-agent.zip",
        "version": "1.5.1",
        "github_url": "https://github.com/watermark-hd/ppc_claude_cli",
        "category": "app",
        "comment": "どんな古いマシンでもAIを使いたい。そんな思いから作りました。エピソードは概要欄で。",
        "comment_en": "Wanted AI to run on even the oldest machine I own. That's the whole reason this exists. The story's in the overview tab.",
        "comment_featured": True,
        "changelog": [
            {
                "date": "2026-09-11",
                "note": "アプリ本体の画面表示を英語対応(英語→日本語の順で併記)。ダウンロードの約7割が海外からだと分かったのに、バナー・プロンプト・確認ダイアログ・プロバイダ切り替え・APIキーのエラーメッセージなどが日本語のみだったため(初回のGeminiキー案内だけは既に英語対応済みだった)。会話内容そのものやツールの実行結果は対象外(AIは元々ユーザーが使った言語で返す仕様のため)。あわせて、2日前に入れたIME確定と送信を取り違える不具合の修正を、実機のPowerBook G4で確認(変換候補を選ぶ際に数秒静止しても誤送信なし)",
                "note_en": "The app's own on-screen text is now bilingual (English first, then Japanese). About 70% of downloads turn out to be from outside Japan, but the banner, prompt, confirmation dialogs, provider-switch messages, and API-key error messages were Japanese only (only the first-run Gemini key walkthrough had been made bilingual before this). Conversation replies and tool-result text are unaffected (the AI already replies in whichever language you write in). Also confirmed on real PowerBook G4 hardware: the IME-commit-vs-submit fix from two days ago holds up (several-second pauses while picking a conversion candidate, no stray submits).",
            },
            {
                "date": "2026-09-11",
                "note": "CLAUDE_PROVIDER=openai を追加。LAN上の速いマシンで動かしているローカルLLM(llama.cpp / Ollama / LM Studio等)に、PowerPC Mac から薄いフロントエンドとして接続できるように(フォーラムで複数回要望あり)。設定は OPENAI_BASE_URL(例: http://192.168.1.50:8080/v1)と、任意の OPENAI_API_KEY(大半のローカルサーバーは無視するのでダミー既定値)、モデル名は既存の CLAUDE_MODEL を流用。http:// のLAN内エンドポイントには証明書検証を要求しない。会話中に /openai でも切り替え可能。ツール呼び出しの対応はローカルモデル側の対応次第だが、普通の会話はどのモデルでも動く",
                "note_en": "Added CLAUDE_PROVIDER=openai — point the agent at any OpenAI-compatible chat/completions endpoint, so a PowerPC Mac can be a thin front-end to a local LLM (llama.cpp / Ollama / LM Studio) on a faster LAN machine (requested more than once on the forum). Config is just OPENAI_BASE_URL (e.g. http://192.168.1.50:8080/v1), an optional OPENAI_API_KEY (most local servers ignore it), and the existing CLAUDE_MODEL for the model name. Plain http:// LAN endpoints need no certificate. Also switchable mid-conversation with /openai. Tool-call support depends on the local model; plain chat works with anything.",
            },
            {
                "date": "2026-09-10",
                "note": "Gemini APIキーの取得を、初回起動時に手順を追って案内するようにした（多くの人がここで挫折していたため）。番号付きチェックリスト → その場でページを開く → 貼り付けたキーを実際に API に投げて有効か検証（「キーが違う」「APIが未有効」「接続できない」を切り分け）→ OKなら ~/.claude-agent-env に保存。案内は英語→日本語の順で併記（共有元のフォーラムが英語のため）",
                "note_en": "First-run Gemini API key setup is now a guided, step-by-step walkthrough — this was the point most people gave up at. A numbered checklist, an offer to open the page in your browser, then the pasted key is actually sent to the API to verify it (telling \"wrong key\" / \"API not enabled\" / \"no connection\" apart) before it's accepted and saved to ~/.claude-agent-env. Shown in English then Japanese, since the forum it's shared from is English.",
            },
            {
                "date": "2026-09-10",
                "note": "AIの返答を一気に表示せず、1文字ずつタイプライター風に流すようにした（速いターミナルだと長い返答が読む前に流れてしまうため。PowerBook G4 からの要望）。既定は1文字6ms、改行で少し長めの間。CLAUDE_TYPE_DELAY で速度調整、0 で従来どおり即表示",
                "note_en": "The assistant's replies now print character by character, typewriter-style, instead of all at once — on a fast terminal a long answer scrolled past before you could read it (a PowerBook G4 request). Default is 6 ms per character with a longer pause at line breaks; tune with CLAUDE_TYPE_DELAY, or set it to 0 for the old instant printing.",
            },
            {
                "date": "2026-09-10",
                "note": "PowerBook G4 実機での入力まわりを改善：（1）1文字打つたびに行全体が再描画されてチラついていたのを、末尾に足すだけの通常時は1文字だけ出す方式に変更（60桁で15文字入力が 584バイト→16バイト）。（2）ターミナルのカーソル位置報告の断片（`;59R` 等）が入力中の行に紛れ込む不具合を修正。（3）日本語入力（IME）で変換確定の Return が、まれに文の途中で送信扱いになる不具合を修正。あわせて CLAUDE_DEBUG_INPUT 設定時に起動直後クラッシュしてターミナルが操作不能になる不具合も修正",
                "note_en": "Input handling on real PowerBook G4 hardware: (1) typing no longer repaints the whole line on every keystroke — the common \"append at the end\" case now prints just the one character (typing 15 chars on a 60-column terminal went from 584 bytes to 16). (2) Fixed stray terminal cursor-position fragments (like `;59R`) landing in the line you're typing. (3) Fixed an IME conversion-confirm Return sometimes counting as \"send\" mid-sentence. Also fixed a startup crash when CLAUDE_DEBUG_INPUT was set that left the terminal stuck.",
            },
            {
                "date": "2026-08-28",
                "note": "Anthropic (Claude) に加えて、クレジットカード不要の無料枠があるGemini (Google) にも対応。セットアップ時にどちらを使うか選べる",
                "note_en": "Added Gemini (Google) support alongside Anthropic (Claude) — Gemini has a free tier with no credit card required. Choose which one to use during setup",
            },
            {
                "date": "2026-08-28",
                "note": "起動コマンドを claude から advisor に変更（特定のAIブランドに縛られない名前に）。会話中に /claude・/gemini でその場でAIを切り替え可能に（会話は引き継がれる）",
                "note_en": "Renamed the command from claude to advisor (not tied to one AI brand). Typing /claude or /gemini mid-conversation now switches providers on the fly, carrying the conversation over",
            },
            {
                "date": "2026-08-28",
                "note": "Geminiへの応答が実機で約30秒かかっていた問題を修正、体感3秒程度に短縮（個体差あり）。Gemini 3系は指定しないと内部思考レベルが最大(HIGH)になる仕様で、軽い質問向けにLOWをデフォルトにした（CLAUDE_GEMINI_THINKING=highで元に戻せる）",
                "note_en": "Fixed Gemini responses taking ~30 seconds on real hardware, down to roughly 3 seconds (varies by device) — Gemini 3 models default to maximum internal reasoning (\"HIGH\") unless told otherwise. Now defaults to \"LOW\" for snappier answers on casual questions (override with CLAUDE_GEMINI_THINKING=high)",
            },
            {
                "date": "2026-08-28",
                "note": "配布用インストーラー(Install.command)がAnthropicのみ対応のままだったのを、Gemini選択・advisorコマンドに対応させ、setup.shと同じ内容に揃えた",
                "note_en": "Brought the distributed double-click installer (Install.command) up to date — it still only knew about Anthropic; now offers the same Anthropic/Gemini choice and advisor command as setup.sh",
            },
            {
                "date": "2026-08-28",
                "note": "Geminiのデフォルトモデルを gemini-3.6-flash から gemini-3.5-flash-lite に変更。実機で試した結果、gemini-3.6-flashの無料枠は1日20回しか無いことが判明したため（flash-liteはもっと大きな無料枠がある）",
                "note_en": "Changed the default Gemini model from gemini-3.6-flash to gemini-3.5-flash-lite — found on real hardware that gemini-3.6-flash's free tier allows only 20 requests per day, while flash-lite has a much larger free daily allowance",
            },
            {
                "date": "2026-08-22",
                "note": "IME経由の日本語入力に0x16のゴミバイトが混入し文字化けする不具合を修正",
                "note_en": "Fixed Japanese IME input getting corrupted by a stray 0x16 byte",
            },
            {
                "date": "2026-08-22",
                "note": "Install.commandの「Enterキーで閉じます」という実態と異なる表示を修正",
                "note_en": "Fixed Install.command's misleading \"Press Enter to close this window\" message",
            },
            {
                "date": "2026-08-22",
                "note": "特定の入力の直後にEnterキーが認識されないことがある不具合を修正",
                "note_en": "Fixed Enter sometimes being silently swallowed right after certain input",
            },
            {
                "date": "2026-08-22",
                "note": "日本語などの入力時、1文字ごとに改行され行編集ができない不具合を修正",
                "note_en": "Fixed every keystroke pushing the terminal down a new line instead of editing in place",
            },
            {
                "date": "2026-08-22",
                "note": "日本語入力時に画面が「◆」で埋まる文字化けを修正",
                "note_en": "Fixed Japanese input filling the screen with garbled \"◆\" characters",
            },
            {
                "date": "2026-08-22",
                "note": "インストーラー再実行時にAnthropic APIキーの再入力を求められる不具合を修正",
                "note_en": "Fixed the installer prompting to re-enter the Anthropic API key when re-run for an upgrade",
            },
            {
                "date": "2026-08-22",
                "note": "矢印キー入力でカーソル移動の代わりに文字が挿入されてしまう不具合を修正",
                "note_en": "Fixed arrow keys inserting garbage characters instead of moving the cursor",
            },
        ],
    },
    {
        "slug": "exfat-tiger-ppc",
        "name": "exFAT for Tiger (PowerPC)",
        "name_en": "exFAT for Tiger (PowerPC)",
        "tagline": "PowerPC Mac OS X 10.4 (Tiger)でexFATドライブの読み書き・マウントができるようにするメニューバーアプリ",
        "tagline_en": "A menu bar app that lets PowerPC Mac OS X 10.4 (Tiger) read, write, and mount exFAT drives.",
        "platform": "PowerPC Mac (Tiger) 向け",
        "filename": "exfat-tiger-ppc.zip",
        "version": "1.0",
        "github_url": "https://github.com/watermark-hd/exfat-tiger-ppc",
        "category": "app",
        "comment": "古いデータが入ったUSBメモリを人から借りたんです、それをPowerMacに挿したら「読めません。フォーマットしますか？」するわけないだろ! その怒りの化身です。",
        "comment_en": "Borrowed a USB drive full of old data from someone. Plugged it into my PowerMac and got “Can't read this. Format it?” — like hell I will! This app is that anger, given form.",
    },
    {
        "slug": "kodama",
        "name": "コダマ (Kodama)",
        "name_en": "Kodama",
        "tagline": "PowerPC Mac (Tiger) 向け、WebKit不使用の超軽量3ペイン型Webリーダー",
        "tagline_en": "An ultra-lightweight 3-pane web reader for PowerPC Macs (Tiger), built without WebKit.",
        "platform": "PowerPC Mac (Tiger) 向け",
        "filename": "Kodama.dmg",
        "version": "0.2.1",
        "github_url": "https://github.com/watermark-hd/kodama",
        "category": "app",
        "comment": "Macって思ったより壊れないんですよ。確かに仕事で使ってましたからメンテナンスはよくしてました。でも倉庫の片隅で眠っているMacたち。減損処理？いやもったいない。無理やり使い道を作った渾身の一作。",
        "comment_en": "Macs don't break as easily as you'd think. Sure, I used to maintain them properly back when they were work machines. But there are still Macs sleeping in the corner of a storage room. Write them off? No way, too good to waste. This is the one I forced a use back into.",
        "changelog": [
            {
                "date": "2026-08-29",
                "note": "v0.2.1: モダンHTTPS用のcurlをアプリに同梱したため、MacPorts / Tigerbrewによる外部curlの導入は不要になりました。特別な理由がなければv0.2.1をご利用ください。",
                "note_en": "v0.2.1: Now bundles a curl capable of modern HTTPS directly in the app, so installing an external curl via MacPorts/Tigerbrew is no longer needed. Use v0.2.1 unless you have a specific reason not to.",
            },
        ],
    },
    {
        "slug": "apython312",
        "name": "Python 3.12",
        "name_en": "Python 3.12",
        "tagline": "PowerPC Mac (Tiger) 向けにビルドしたCPython 3.12.11 + pip。再配置可能な個人ビルド",
        "tagline_en": "A relocatable, unofficial build of CPython 3.12.11 + pip for PowerPC Mac OS X 10.4 (Tiger).",
        "platform": "PowerPC Mac (Tiger) 向け",
        "filename": "apython312.dmg",
        "github_url": "https://github.com/watermark-hd/apython3",
        "category": "app",
        "version": "3.12.11",
        "comment": "3.12だけ、上にも下にもあるのに無かったんです。バージョンが違うと地味に色々変わるので、手元のPowerBook G4で使うにはこれが要る、と思って作りました。コンパイルとエラー潰しで丸一日溶けました。",
        "comment_en": "3.12 was the one version that just didn't exist — everything above and below it did. Python versions quietly change more than people think, and I wanted this exact one on my PowerBook G4, so I built it myself. Burned a full day compiling and chasing down errors.",
    },
    {
        "slug": "tiger-quicklook",
        "name": "Tiger QuickLook",
        "name_en": "Tiger QuickLook",
        "tagline": "Mac OS X 10.4 Tiger 実機向けの軽量Quick Look代替。Finderでファイルを選んでSpaceキーでプレビュー（画像・PDF・テキスト・Officeなど）",
        "tagline_en": "A lightweight Quick Look substitute for Mac OS X 10.4 Tiger — select a file in the Finder, press Space, and a preview appears (images, PDF, text, Office and more).",
        "platform": "PowerPC Mac (Tiger) 向け",
        "filename": "TigerQuickLook.dmg",
        "github_url": "https://github.com/watermark-hd/tiger-quicklook",
        "category": "app",
        "version": "0.4",
        "comment": "軽いからという理由でTigerを使い続けるためにも便利すぎるこの機能はぜひ欲しかった。パッチを当ててLeopardにしようかとも考えましたが、非力なマシンで、Tigerのまま実装したかったんです。まだまだアップデート予定ですが、ある程度のフォーマットには対応しています。",
        "comment_en": "I keep using Tiger because it's light, and I really wanted this far-too-convenient feature while I'm at it. I thought about patching my way up to Leopard, but I wanted to build it on Tiger, on the underpowered machine as it is. Plenty of updates still to come, but it already handles a decent set of formats.",
        "changelog": [
            {
                "date": "2026-09-09",
                "note": "v0.4: プレビュー中の矢印キー移動が、表示できないファイル（壊れた xlsx や本文を取り出せない Office ファイルなど）で止まらず、次の表示できるファイルまで飛ぶように変更（止まると前のプレビューが残って別ファイルに見えるため）。行き止まりでは音で知らせます。あわせて、アプリ内の文言（メニュー・警告・ツールチップ）を日本語と英語の併記にしました",
                "note_en": "v0.4: arrow-key navigation now skips files it can't preview (a broken xlsx, an Office file whose text can't be extracted) and continues to the next one that displays, instead of stopping with the previous file's preview still on screen. A beep marks the end of the run. The app's own text (menu, alerts, tooltip) is now shown in both English and Japanese.",
            },
            {
                "date": "2026-09-09",
                "note": "v0.3: プレビュー中の矢印キー移動で、ウィンドウを作り直さず中身だけ差し替えるように変更（ちらつきが減り、ウィンドウの位置とサイズを保持）",
                "note_en": "v0.3: arrow-key navigation now swaps just the content instead of recreating the window (less flicker, keeps the window's position and size).",
            },
            {
                "date": "2026-09-09",
                "note": "v0.2: 対応形式を拡張（追加ライブラリなし、Tiger標準の textutil / unzip のみ）。画像に TIFF / GIF / BMP、テキストは .md ほか .csv / .json / .xml / 各種ソースと拡張子なしのテキスト、旧Office（DOC / RTF / HTML は textutil 経由）、新Office（DOCX / PPTX / XLSX / ODT / ODS / ODP は ZIP 内の本文XMLを抽出）。目的は「整形」ではなく「名前だけでは思い出せないファイルの中身確認」。あわせて、プレビュー中に ← / → / ↑ / ↓ で同じフォルダ内の前後のファイルへ移動できるように（Leopard の Quick Look と同じ操作感）",
                "note_en": "v0.2: expanded the supported formats (no new libraries — only Tiger's own textutil / unzip). Images gain TIFF / GIF / BMP; plain text now covers .md plus .csv / .json / .xml / many source types and extension-less text; legacy Office (DOC / RTF / HTML via textutil); modern Office (DOCX / PPTX / XLSX / ODT / ODS / ODP by pulling the body XML out of the zip). The goal is identifying a file you can't place by name, not faithful rendering. Also: while a preview is open, ← / → / ↑ / ↓ move to the previous/next file in the same folder (like Leopard's Quick Look).",
            },
        ],
    },
    {
        "slug": "retrocert",
        "name": "RetroCert",
        "name_en": "RetroCert",
        "tagline": "古いMacの証明書ストアを、署名検証つきで安全に更新するツール。ただし効果は限定的です（詳細は概要欄で）",
        "tagline_en": "Refreshes an old Mac's root certificate store, with signature verification even over plain HTTP — though the real-world payoff turned out limited (details in the overview).",
        "platform": "PowerPC Mac (Tiger以降) 向け",
        "filename": "RetroCert.zip",
        "version": "1.0",
        "github_url": "https://github.com/watermark-hd/RetroCert",
        "category": "app",
        "comment": "「証明書が古くて繋がらないなら、証明書を直せばいいのでは」と思って作りました。実際やってみたら、思ったほどの魔法にはなりませんでした。それでも仕組みは残しておく価値があると思い、部品として使ってもらえればと公開しました。",
        "comment_en": "Started from \"if it's just an expired certificate, why not fix the certificate.\" Turned out not to be the magic fix I hoped for. Still thought the mechanism underneath was worth keeping around, so I'm publishing it as something others might reuse as a part.",
        "changelog": [
            {
                "date": "2026-09-12",
                "note": "初版公開。実機のPowerMac G4(Tiger)で本番VPS経由の動作を検証し、信頼済み証明書を158件から238件に拡張(RSAルート80件を追加。ECCルート41件はTigerの証明書ライブラリがECC非対応のためスキップ)",
                "note_en": "Initial release. Verified end to end on a real PowerMac G4 (Tiger) against the production VPS: grew the trust store from 158 to 238 entries (80 RSA roots added; 41 ECC roots skipped, since Tiger's certificate library predates ECC support).",
            },
        ],
    },
    {
        "slug": "mac-snow-leopard-linux",
        "name": "Mac OSX Snow Leopard風 Linux",
        "name_en": "Mac OS X Snow Leopard-inspired Linux",
        "tagline": "MX Linux ベース。OSX 10.4～10.6 当時のシンプルなUIを再現したディストリビューション",
        "tagline_en": "A MX Linux-based distro that recreates the simple UI of Mac OS X 10.4–10.6.",
        "platform": "Linux",
        "filename": None,
        "category": "project",
    },
    {
        "slug": "policy-log-jp",
        "name": "Policy-log-jp",
        "name_en": "Policy-log-jp",
        "tagline": "政策の流れを時系列で追う。一次資料のみを使用した偏向しない政策ポータル",
        "tagline_en": "A policy portal that traces government decisions in chronological order using primary sources only.",
        "platform": "ウェブサイト",
        "url": "https://policy-log.jp",
        "filename": None,
        "category": "project",
    },
]

APPS_BY_SLUG = {app["slug"]: app for app in APPS}
